### ISSUE TITLE
Make generated documentation deterministic

### ISSUE THREAD

**Issue by ptomato** [hotdoc/hotdoc#114]
Now that we have the git-upload extension, it would be nice if the generated documentation were made deterministic so that the commits were as small as possible. For example, here's a commit from my documentation with no actual changes to the site: https://github.com/endlessm/eos-knowledge-lib/commit/3c5a91af59a41e9221d3990f4c6f927ddb9435bc

Looks like it could be solved by making sure that `dict`s in some places are sorted before output.

**Comment by MathieuDuponchelle** [comment]
+1, that should indeed be easy

**Comment by eli-schwartz** [comment]
Does the linked PR make it fully deterministic for you?
