### ISSUE TITLE
Feature request: Encourage compilation of big code examples

### ISSUE THREAD

**Issue by pwithnall** [hotdoc/hotdoc#12]
If I put a big code example in my documentation, I want to be able to compile it every time I build my module, and run unit tests against it with `make check`; otherwise it’s basically guaranteed to bitrot and make my documentation look bad.

It would be great if hotdoc allowed including code blocks in a way which encourages this. My initial thoughts are:
 * Require big code examples to be a separate code file (for example, a C file), which is ready to compile (i.e. has full `#include`s, etc.) and hence can be built and tested from the makefile.
 * Have syntax in hotdoc for including part of that code file, either a range of line numbers, or a set of named functions (that would be a bit harder though).
 * Include a complete copy of the source code (with licencing information; see issue #9) in the outputted documentation, and link to that from the part inlined in the documentation.
 * Bonus feature: have syntax in hotdoc for highlighting parts of the code example which are mentioned in the text, such as a particular line which demonstrates what’s being documented.

**Comment by MathieuDuponchelle** [comment]
Include a complete copy of the source code:

There's an extension (sort of) for that @ https://github.com/MathieuDuponchelle/hotdoc_extensions/blob/master/source_code_linker.py

That's actually the only extension, I think it still works with the current version.

regarding examples, the syntax I will implement is {{include_this}} , I haven't thought of a syntax for including only a subrange of the source file but that's a good idea, what would you propose on the markdown syntax side ? FWIW I chose {{..}} as it's the nicest syntax I could find for inclusion, it's in multimarkdown and named "transclusion" : http://fletcher.github.io/MultiMarkdown-4/transclusion.html

**Comment by MathieuDuponchelle** [comment]
Maybe {{include_this[x:y]}} , python syntax should be familiar to most ?

**Comment by pwithnall** [comment]
That would work, although the `[x:y]` syntax should be kept separate from the `include_this` filename, since it could be part of a valid filename.

An alternative would be the `![][]` syntax currently used by gtk-doc for including image files (see Example 3-3 on https://developer.gnome.org/gtk-doc-manual/unstable/documenting_syntax.html.en#documenting_syntax). The metadata about the inclusion (lines to include) could be in the first set of brackets: `![first_line=x,last_line=y][source-code.c]`. The advantage of the gtk-doc syntax is that it means there’s a single syntax for including files (images, code files, whatever), and the metadata about the inclusion is kept syntactically separate from the source code filename. Using keywords for specifying the lines to include means that we could add other methods of selecting what to include in future, for example: `![include_function=foo,include_function=bar,include_comments=False,highlight_line=15][source-code.c]`.

That’s one suggestion, anyway. It might be worthwhile to look at what [`listings`](http://texdoc.net/texmf-dist/doc/latex/listings/listings.pdf) supports (see §4.4), since it’s been around for a while, so they will have added all the most useful ways of specifying which bits of a source code file to display.

**Comment by MathieuDuponchelle** [comment]
One could escape the [x:y] characters if really needed

**Comment by pwithnall** [comment]
Certainly. What about the rest of my suggestions?

**Comment by MathieuDuponchelle** [comment]
-> Require big code examples [...] : that's not something I want to *require*
-> Link to complete copy of the source code -> that's pretty much what the source code linker extension is for, will just need to be extended for linking included files too
-> syntax in hotdoc for highlighting parts of the code example -> there shouldn't be a syntax for that, but a generic way to generate "linked" source code a la doxygen and that's a separate feature.

**Comment by pwithnall** [comment]
> -> Require big code examples [...] : that's not something I want to require

I phrased that badly. I think allowing inline and in-file examples should be supported, because sometimes it’s just not possible to make a code example compilable — but I think that making sure examples are compilable should be strongly encouraged through hotdoc’s documentation and examples.

> -> Link to complete copy of the source code -> that's pretty much what the source code linker extension is for, will just need to be extended for linking included files too

Brilliant. I’m sorry I haven’t had time to fully explore the existing hotdoc features.

> -> syntax in hotdoc for highlighting parts of the code example -> there shouldn't be a syntax for that, but a generic way to generate "linked" source code a la doxygen and that's a separate feature.

I’m not familiar with doxygen enough. I mean something like the image at the bottom of [this SO answer](http://tex.stackexchange.com/questions/15237/highlight-text-in-code-listing-while-also-keeping-syntax-highlighting/49309#49309) (but ignore the syntax, because achieving that with `listings` is a total pain).

**Comment by MathieuDuponchelle** [comment]
Just a quick note, @thiblahute implemented a first version of {{include_this}} in https://github.com/MathieuDuponchelle/hotdoc/commit/f2d814f4729b59cacf21a75d9d156649bde3d821 amongst other nice things , this will be part of the 0.5 release :D

**Comment by MathieuDuponchelle** [comment]
The full feature is now  working, with fancy syntax such as:

```
{{ include.c#my_function[2:4] }}
```

which includes the lines 2 to 4 in the scope of my_function in include.c , which can thus be compiled separately.

Thanks for the report, closing
