### ISSUE TITLE
Question: Hotdoc vs. Yelp?

### ISSUE THREAD

**Issue by mckinney-subgraph** [hotdoc/hotdoc#125]
I am not sure if this is the right place to ask but I am curious what the relationship between `Hotdoc` and `Yelp` is, if any? Specifically, does the `Hotdoc` roadmap include generating documentation that can be consumed by `Yelp`? 

What piqued my interest was that I noticed that the developer had submitted a `Mallard` reader for `pandoc`, presumably for the purpose of converting existing GNOME-related documentation from `Mallard` to `CommonMark`. I have used `pandoc` myself to generate documentation that targeted different formats (PDF, HTML, Epub, and Yelp via Docbook). 
 
I am taking a look at `Mallard` and `Yelp` again and trying to figure out if it will be continue to be used as a format for writing GNOME-related documentation or if `CommonMark` will be the preferred format in the future. I don't know if you can answer that question for me or direct me to somebody who can.

**Comment by MathieuDuponchelle** [comment]
Let's say that opinions diverge, I personally see no reason to write Mallard over Docbook, and writing xml in any way shape or form doesn't make it easy for potential contributors to chime in

**Comment by mckinney-subgraph** [comment]
Great, thanks for the info! :)
