### ISSUE TITLE
Bad position of the `>` icon in the menu items when long text

### ISSUE THREAD

**Issue by aleb** [hotdoc/hotdoc#136]
For example:
<img width="219" alt="screen shot 2018-09-07 at 12 33 11" src="https://user-images.githubusercontent.com/505582/45214256-40670080-b29a-11e8-832e-4beda0a1cc95.png">

**Comment by MathieuDuponchelle** [comment]
I can reproduce that, thanks, probably need to tweak text wrapping somehow

**Comment by MathieuDuponchelle** [comment]
@aleb , you'll need thibault to rebase the lumen theme, but it should behave as expected now, thanks again!
