### ISSUE TITLE
Add a way to describe flexbox based list in markdown

### ISSUE THREAD

**Issue by thiblahute** [hotdoc/hotdoc#139]
The idea is to be able to produce cover pages such as descibed in https://wiki.gnome.org/Design/Whiteboards/DeveloperDocs?action=AttachFile&do=get&target=gnome-developer.png with pure markdown.

The idea would be to add a simple list synthax to describe list that should be flexboxified (something similare to how we display subpages with thumbnails), we discussed using something like:

```
# Developer tutorials

& ![Making application menu](document_menu.png) ...
& ![GNotification](gnotification.png) ....
& ![Search provider](search_provider.png) ...
```

which would render like:

![image](https://user-images.githubusercontent.com/83553/47161428-61266b00-d2c8-11e8-9c80-c5d9a30c84df.png)

**Comment by svitoz** [comment]
Might want to implement [Special Attributes from PHPs markdown extra](https://michelf.ca/projects/php-markdown/extra/#spe-attr) and specify whatever apearance you want website-wide with css classes.

**Comment by MathieuDuponchelle** [comment]
@svitoz , I think this approach kind of goes against markdown's design goals (https://talk.commonmark.org/t/consistent-attribute-syntax/272/ for a discussion around this), I'd much rather have a new block type to be honest :)

**Comment by MathieuDuponchelle** [comment]
I picked the following syntax:

```
~ [![](assets/img1.jpg)](subpage.md) [](subpage.md)
~ [![](assets/img1.jpg)](subpage.md) [The same page](subpage.md)
~ [![](assets/img1.jpg)](subpage.md)
~ [![](assets/img1.jpg)](subpage.md) The same page, again
```

ie, `~` to mark a "flexible list"

**Comment by thiblahute** [comment]
\o/

**Comment by bastianilso** [comment]
Does this work in the hotdoc version that pip installs `pip install --user meson hotdoc` yet?

**Comment by MathieuDuponchelle** [comment]
@bastianilso , no you need master, I want to merge my optimization of the search index creation before making a new release fwiw
