### ISSUE TITLE
Can't find symbols, can't reference symbols / Howto link md documentation to symbol code?

### ISSUE THREAD

**Issue by mv0** [hotdoc/hotdoc#154]
Hi,

I've tried using meson module for hotdoc, tried using hotdoc manually using a simple project and tried using https://github.com/hotdoc/test_hotdoc.

It seems that the doc directory where the html files are generated are different that the directory where the comments are actually stored. I can't seem to find a way to link the markdown documentation with the  symbols generated from code.

For instance for the test_hotdoc project the following are generated: doc -> which contains devhelp and html directories but there's a hotdoc-private-HotdocTest-1.0/ directory where the comments from the code are the found. I browse either html/index.html and/or devhelp/index.html. Searching using the search bar doesn't print any symbol (at this stage I'm not sure if it would normally). 

It could be that I might be missing something, but the test_hotdoc doesn't appear to be working as other projects I've tried: code symbols comments are under hotdoc-private-project-name under comments directory, but nowhere are those linked and/or referenced in the html documentation itself. The documentation for hotdoc is .. a bit lacking or I couldn't find a easy way where that is explained. 

For instance using [description](function_call) will generate a link to a function_call html page in the doc build directory. 

I'm also missing the ability to have a full index of function calls: adding c-index in sitemap or gi-index in sitemap doesn't help. 

PS: For test_hotdoc to work I had to comment test-other-file.h otherwise get an YAML err.

**Comment by mv0** [comment]
Turns out that the reason that the symbols file weren't added is because there's no header file it. I've always used just c files without header files. If the headers are empty/non-existent (which is valid in some cases)/no-specified hotdoc won't generate the html file for it.

**Comment by MathieuDuponchelle** [comment]
Yes, the C extension will only document symbols that are exposed publicly, which usually means a definition is present in headers :)

**Comment by mv0** [comment]
Okay, I guess this is intended. :+1: Thanks for the help!
