### ISSUE TITLE
API docs sidebar / navigation not scrollable sometimes in Safari

### ISSUE THREAD

**Issue by ePirat** [hotdoc/hotdoc#158]
I discovered this issue a while ago with the meson documentation, for example on http://mesonbuild.com/Release-notes-for-0-50-0.html it is sometimes impossible to scroll the left sidebar content in Safari, annoyingly sometimes it is perfectly aligned so it is impossible to easily see that there is even something to scroll and not the end of the sidebar.

Using Safari Version 12.1.1 (14607.2.6)

**Comment by MathieuDuponchelle** [comment]
Does the scrollbar appear at all when hovering the left sidebar? Can you see any error messages in the console?

**Comment by ePirat** [comment]
Not sure if meson updated the docs or a Safari update or just luck but I can not reproduce anymore at the moment.

**Comment by MathieuDuponchelle** [comment]
OK, can we close that for now then?

**Comment by ePirat** [comment]
Yes
