### ISSUE TITLE
gtk-doc #GObjectClass.virtual() references not supported

### ISSUE THREAD

**Issue by ystreet** [hotdoc/hotdoc#164]
Example output:
```
WARNING: [core]: (gtk-doc-bad-link): /home/matt/Projects/gst/gst-build/subprojects/gst-plugins-base/gst-libs/gst/gl/gstglcolorconvert.c:1303:36: Trying to link to non-existing symbol ‘GstBaseTransformClass.fixate_caps’
01301: * @other: (transfer full): the #GstCaps to fixate
01302: *
01303: * Provides an implementation of #GstBaseTransformClass.fixate_caps()
                                        ^
01304: *
01305: * Returns: (transfer full): the fixated #GstCaps
```

gtk-doc itself has a bullet point about this syntax in its manual on https://developer.gnome.org/gtk-doc-manual/stable/documenting_syntax.html.en :
`Use #Struct.field to refer to a field inside a structure and #GObjectClass.foo_bar() to refer to a vmethod.`

**Comment by MathieuDuponchelle** [comment]
This works for me too. Are you building the subproject on its own? If so, you need the relevant devhelp indexes (in that case the gstreamer devhelp index) available system-wide in order to resolve links.

**Comment by MathieuDuponchelle** [comment]
The link seems to be rendered all right in the CI at least: https://ystreet.pages.freedesktop.org/-/gst-plugins-base/-/jobs/307624/artifacts/documentation/gst-plugins-base-gl-1.0/gstglcolorconvert.html?gi-language=c#gst_gl_color_convert_fixate_caps

**Comment by ystreet** [comment]
I was building the subproject on its own and I do have devhelp docs installed system-wide already for GStreamer and friends based on the gtk-doc documentation.  Is there a specific file devhelp I need to look at for resolving these links?

I can see I have GStreamer things in `/usr/share/gtk-doc/html/` but not in `/usr/share/devhelp/*`

**Comment by ystreet** [comment]
I also tried building all the docs and these links are still not generated correctly.

**Comment by MathieuDuponchelle** [comment]
This should be fixed now, if you don't mind testing again that would be nice :)

**Comment by ystreet** [comment]
How do I test exactly?

**Comment by MathieuDuponchelle** [comment]
latest gst-build, latest hotdoc, build the whole doc (that will generate a .devhelp2 we can then get links from), enter the uninstalled environment (it now sets XDG_DATA_DIRS), build the gl-docs on its own -> hopefully no more warnings

**Comment by MathieuDuponchelle** [comment]
Closing, please reopen if you find time to test and it still doesn't work for you :)
