### ISSUE TITLE
Newest hotdoc fails importing yaml

### ISSUE THREAD

**Issue by jpakkane** [hotdoc/hotdoc#168]
Trying to build the Meson documentation on Debian unstable and Hotdoc from pip fails with the following error:

    Module 'yaml' has no attribute 'FullLoader'.

This is on `core/tree.py` line 546.

**Comment by MathieuDuponchelle** [comment]
Hey @jpakkane this was fixed in https://github.com/hotdoc/hotdoc/commit/b80843058a2ece0c97764256156374af1e1d9426 , will be part of the next release, for now you can fix this with `python3 -m pip install pyyaml --upgrade` :)

Please reopen if needed
