### ISSUE TITLE
Missing public members in GstBinClass documentation

### ISSUE THREAD

**Issue by ocrete** [hotdoc/hotdoc#185]
The gtk-doc generated documentation for GstBinClass has the add_element, remove_element, handle_message, deep_element_added and remove_element_added members, but the hotdoc generated one at https://gstreamer.freedesktop.org/documentation/gstreamer/gstbin.html?gi-language=c#class-structure doesn't.

**Comment by ocrete** [comment]
ah it's in a separate section!

**Comment by MathieuDuponchelle** [comment]
Well that was quick :) and yes @thiblahute and I debated this at some point, but I figured if we had a separate section for virtual methods we could split them out from the class structure, arguably a bit misleading however
