### ISSUE TITLE
COPYING file missing from tarballs

### ISSUE THREAD

**Issue by hadess** [hotdoc/hotdoc#186]
And the tarballs on github seem to lag behind the pypi ones:
https://pypi.org/project/hotdoc/#history
vs.
https://github.com/hotdoc/hotdoc/releases

(the snapshots at https://github.com/hotdoc/hotdoc/tags aren't usable because the submodules are missing)

**Comment by MathieuDuponchelle** [comment]
re tarballs, the pypi ones are authoritative. On github, if you click on "show 4 newer tags" you'll also see 0.10.0, I'm not entirely sure why 0.9.3 is marked as an actual release on github, @thiblahute ?

Re COPYING file, good catch thanks, https://github.com/hotdoc/hotdoc/commit/6780ce3aed475300d3e87ead8e6c4062a4467f38
