### ISSUE TITLE
plain structures are not generated correctly

### ISSUE THREAD

**Issue by ceyusa** [hotdoc/hotdoc#188]
See, for example, the bitstream parser: https://gstreamer.freedesktop.org/documentation/gst-plugins-bad-codecparsers/gsth264parser.html?gi-language=c

Almost all the structures are documented, but that documentation doesn't appear in html

**Comment by MathieuDuponchelle** [comment]
Thanks for reporting :) Hesitated to say "NOTABUG" and that the docstrings' titles should be prefixed with an underscore, but in practice the C extension only supports gtk-doc and should follow the convention.
