### ISSUE TITLE
0.11.1: build fails

### ISSUE THREAD

**Issue by kloczek** [hotdoc/hotdoc#198]
Because I see setup.py in root directory I';m trying to use standard method which is failing:
```
+ /usr/bin/python3 setup.py build '--executable=/usr/bin/python3 -s'
Traceback (most recent call last):
  File "setup.py", line 110, in <module>
    for filename in os.listdir(CMARK_SRCDIR):
FileNotFoundError: [Errno 2] No such file or directory: '/home/tkloczko/rpmbuild/BUILD/hotdoc-0.11.1/cmark/src'
```
Probably I'm trying to build that using wrong method so question is: how hotdoc should be build? :P

**Comment by MathieuDuponchelle** [comment]
Hey, you're late, it's 0.12.0 now :P hotdoc has submodules, you need to run git submodule update --init but `setup.py` should be taking care of this (see `require_clean_submodules`) The exact same command you shared works on my end for what it's worth. Are you trying to build a package for a distribution?

**Comment by kloczek** [comment]
Looks like  cmarlk is standalone project which even provide sproper pkgconfig interface.
I think thaat instead linking repos better would be just untangle that and use pkgconfig to detect that cmarl devel resources are installed.

**Comment by MathieuDuponchelle** [comment]
@kloczek hotdoc maintains its own cmark fork

**Comment by MathieuDuponchelle** [comment]
@kloczek closing, please reopen if you have more information

**Comment by kloczek** [comment]
IMO if you forked cmark fork you should add it straight into your code or build it as something new as standalone project.

**Comment by MathieuDuponchelle** [comment]
I don't understand what you mean, but unless you can offer a good reason why this is indeed only a matter of opinion :)

**Comment by MathieuDuponchelle** [comment]
Note that the sdist package has the submodule checked out, you might be looking to download the tarball from https://pypi.org/project/hotdoc/0.12.2/#files instead

**Comment by kloczek** [comment]
Did you try to sbmit yout patches to cmark?

**Comment by MathieuDuponchelle** [comment]
A few times yes. github ended up cherry-picking those in their own cmark fork, but the cmark maintainer was worried about intrusiveness.

**Comment by kloczek** [comment]
I've asked him as well because I want to avoid to have cmark packages or one standalone and second one bundled.
https://github.com/commonmark/cmark/issues/351
IMO it would be good to invest a bit time to have necessary functionalities into reguler cmark.
If you can help on that pleas do that :)
IMO it would be good to stat pushing changes needed by you in some smaller chunks (?)

**Comment by thiblahute** [comment]
Well have a look at https://github.com/commonmark/cmark/pull/123 to see how much work has been put in trying to get that in since 2016. [Github]( https://github.blog/2017-03-14-a-formal-spec-for-github-markdown//) themselves ended up [forking](https://github.com/github/cmark-gfm) cmark because of that specific patch not being upstreamed.

**Comment by MathieuDuponchelle** [comment]
@kloczek I understand bundling is considered problematic, but pragmatism has its virtues, we can't force a maintainer to accept a patchset he's not interested in. You should tell us a bit more about your use case, what distribution are you making a package for? What's the policy of that distribution with respect to bundling? What are the conditions for making exceptions? Do you have any technical difficulties with building hotdoc? Have you checked out the pypi package which has all the sources in tree?

**Comment by kloczek** [comment]
Look on https://github.com/commonmark/cmark/issues/351
Maintainet is opened on review and commit changes in smaller chunks.
Please try again submit necessaty changes :)

**Comment by kloczek** [comment]
Yes I have dificulties,. One of those difficulties is relateto to be not able use regular cmark.
cmark is used by several other packages (hotdoc is not only consumer of that library).

**Comment by MathieuDuponchelle** [comment]
@kloczek if you won't answer any of my questions except in the vaguest of terms, I don't see much of a point in continuing this discussion.

**Comment by kloczek** [comment]
I've answered on your question.

**Comment by MathieuDuponchelle** [comment]
@kloczek I can't tell if you're a troll or just very good at making people annoyed, in doubt:

> You should tell us a bit more about your use case, what distribution are you making a package for? What's the policy of that distribution with respect to bundling? What are the conditions for making exceptions? Do you have any technical difficulties with building hotdoc? Have you checked out the pypi package which has all the sources in tree?

The only question you've half answered is with:

> Yes I have dificulties,. One of those difficulties is relateto to be not able use regular cmark.
cmark is used by several other packages (hotdoc is not only consumer of that library).

But that's a very vague statement, not even in answer to my question, not being able to use "regular" cmark isn't a blocker for building hotdoc, simply potentially an issue for getting the package accepted.

**Comment by kloczek** [comment]
Please stop focusing on me (I'm not the subject here) and try to do what I've been asking you which is submitting your adaptation to cmock.
I've not been trying to build hotdoc with standalone cmock because you are not offering such option and for now it will be necessary to modify hotdoc to even try to build that that way.
Q: it is any API obstacle in way how you are using cmock which would disallow now such build?

**Comment by MathieuDuponchelle** [comment]
> Please stop focusing on me (I'm not the subject here) and try to do what I've been asking you which is submitting your adaptation to cmock.

What makes you think you can order me around? If you need something done just do it, otherwise be nice and courteous and answer the questions whoever you're demanding something from is asking!

> I've not been trying to build hotdoc with standalone cmock because you are not offering such option and for now it will be necessary to modify hotdoc to even try to build that that way.

This sentence makes no sense. You cannot compile against regular cmark, if you had taken the time to look at the PR @thiblahute linked, you would have noticed it adds new API.

> Q: it is any API obstacle in way how you are using cmock which would disallow now such build?

see above

**Comment by kloczek** [comment]
> What makes you think you order me around?

Maybe you didn't notice but I've started from worde "Pl,ease".
Is it in your culture such begin of the sentence means order to do something????

**Comment by MathieuDuponchelle** [comment]
> Is it in your culture such begin of the sentence means order to do something????

Let's say that your phrasing is unusual and leave it at that
