### ISSUE TITLE
Wrong capitalization in "Edit on github" extension

### ISSUE THREAD

**Issue by radioactiveman** [hotdoc/hotdoc#215]
The `Edit on github` extension does not capitalize GitHub correctly.
Please use `GitHub` and `GitLab` consistently in the whole class and especially the button label.

Thanks.

https://github.com/hotdoc/hotdoc/blob/83d0c70ecb9e0224ec67dcf7c6c5cfee8d049288/hotdoc/extensions/edit_on_github/edit_on_github_extension.py#L99-L103

**Comment by MathieuDuponchelle** [comment]
PR welcome :)

**Comment by MathieuDuponchelle** [comment]
tnx :)
