### ISSUE TITLE
Incompatible with Python 3.9 and higher

### ISSUE THREAD

**Issue by nanonyme** [hotdoc/hotdoc#217]
This project now does not work with Python 3.9 or higher because networkx==1.11 is not compatible with it. Please consider making a release as apparently trunk already supports newer networkx https://github.com/hotdoc/hotdoc/issues/208.

**Comment by eli-schwartz** [comment]
A release has been made.

**Comment by MathieuDuponchelle** [comment]
yes, haven't tested with 3.9 but networkx has indeed been bumped with the latest release, closing tnx :)
