### ISSUE TITLE
Drop cchardet dependency

### ISSUE THREAD

**Issue by garnacho** [hotdoc/hotdoc#245]
The cchardet python library seems to have trouble with Python >=3.10, and fails to build with Python >= 3.11:

https://github.com/PyYoshi/cChardet/issues/77
https://bugzilla.redhat.com/show_bug.cgi?id=2021804

This wouldn't usually be a problem for long, but cchardet seems to be abandoned. Other projects that depend on it have jumped ship and distributions like Fedora no longer package this python library. This makes it impossible to install hotdoc from pip or other sources on Fedora 37 and presumably other recent distros.

Hotdoc should probably follow those steps and drop the cchardet dependency (e.g. assume UTF-8 input in the C extension), or look for a replacement.

**Comment by nanonyme** [comment]
Right, the suggested change would be to either switch to charset-normalizer (https://charset-normalizer.readthedocs.io/en/latest/user/getstarted.html#basic-usage) and drop Python 3 support for Python 3.4 and 3.5 (and switch to only non-EOL versions 3.6 and newer) or drop support for other encodings than UTF-8.

**Comment by nanonyme** [comment]
@MathieuDuponchelle which do you think would be lesser evil?

**Comment by nanonyme** [comment]
Looks like this project is claiming in setup.py to support completely different versions it actually tests.

**Comment by MathieuDuponchelle** [comment]
oof, my bad for not replying earlier, thanks @nanonyme
