### ISSUE TITLE
Move site navigation to an iframe

### ISSUE THREAD

**Issue by iamtakingiteasy** [hotdoc/hotdoc#254]
This is an issue specific to https://gstreamer.freedesktop.org/documentation ; gstreamer community redirects issues here, but it likely to apply to hotdoc in general. 

If documentation is loaded without JS enabled, sidebar content is not rendered at all. There is no markup for navigation in html returned by the server, everything is added dynamically by JS scripts. There probably should be plain \<details\/\> elements in static html returned on initial request instead. 

If JS is enabled, scrolling sidebar content is often unpredictable, scroll location may jump and overshoot expected target, unlike native scrolling. This is mostly triggered by mouse cursor exiting and entering the sidebar area, followed by scrolling attempt. I assume it is some attempt to implement horrific kinetic scrolling? Might be incorrect scroll position persistence too. But there probably no good reason to even attempt to replace native browser scrolling with top-offset shenanigans, it only destroys usability. Use scrollTo to scrollIntoView if you want to navigate to element with JS in some cases, but plain HTML anchors will often work even better. Do not prioritize style (of scroll indicators) over substance (usability of scrolling), this is documentation, it's primary function is to provide information, not to be fancy and unusable.

Current workaround: 

1. Let page load with JS
2. Remove `mousewheel`, `wheel` and `scroll` listeners on `#mCSB_1`  and `#mCSB_1_container`
3. Remove `top` css property (if any) on `#mCSB_1_container`
4. Add `overflow: auto` css property on `#mCSB_1`
5. Delete `#mCSB_1_scrollbar_vertical` element

This allows sane scrolling and searching for items of interest with native browser scroll and search and not dependent on JS to function. If absolutely must, you can style scrollbar itself with browser-specific selectors too.

Userscript until issue is resolved:
```js
// ==UserScript==
// @name         Native scrolling
// @namespace    https://gstreamer.freedesktop.org/documentation
// @version      0.1
// @description  Makes scrolling native on navigation
// @author       iamtakingiteasy
// @match        https://gstreamer.freedesktop.org/documentation/*
// @icon         https://gstreamer.freedesktop.org/documentation/assets/images/favicon.png
// @grant        none
// @run-at       document-body
// ==/UserScript==

(function() {
    'use strict';
    EventTarget.prototype._addEventListener = EventTarget.prototype.addEventListener;
    EventTarget.prototype.addEventListener = function(a, b, c) {
        if (a === 'scroll' || a === 'wheel' || a === 'mousewheel') {
            return
        }

        return this._addEventListener(a,b,c);
    };

    const root = document.body.querySelector('#page-wrapper');

    let changes = 0;

    new MutationObserver((list, self) => {
        for (const m of list) {
            for (const el of m.addedNodes) {
                // get back native scroll
                if (el.id === 'mCSB_1') {
                    const tgt = el;
                    const tgtNested = el.children[0];
                    tgt.style.overflow = 'auto';
                    tgtNested.style.top = '0px !important';

                    // prevent top position change
                    new MutationObserver((list, self) => {
                        tgtNested.style.top = '0px !important';
                    }).observe(tgtNested, { attributes: true, attributeFilter : ['style'] });

                    // expand all categories to simplify searching. Slow, but makes reading the docs convenient.
                    // all contents should ideally be already part of static HTML file returned by the server.
                    // collapsing should be handled with <details/> elements.
                    setTimeout(() => tgtNested.querySelectorAll('.sidenav-toggle').forEach(x => x.click()), 0);
                    setTimeout(() => tgtNested.querySelectorAll('.collapsed').forEach(x => x.click()), 0);

                    changes++;
                }

                // prevent scroll position change when expanding elements
                if (el.id === 'mCSB_1_scrollbar_vertical') {
                    el.parentElement.removeChild(el);

                    changes++;
                }

                // no need for observer anymore
                if (changes === 2) {
                    self.disconnect();
                }
            }
        }
    }).observe(root, { childList: true, subtree: true });
})();
```

But ideally documentation should not require any dynamic functionality and combating JS with more JS is hardly a sustainable solution.

**Comment by MathieuDuponchelle** [comment]
@iamtakingiteasy yes I agree, the custom scrollbar usage should be removed, the intent here was simply to have styled scrollbars, not kinetic scrolling (much less of the horrific kind) :)

Note that the idea with the dynamically loaded site navigation is to avoid absolutely blowing up the size of the documentation, both in terms of the individual file sizes and of the overall collection, there are thousands of files in there and we simply can't have them all statically listed. I'm not sure what you mean by `<details>` in this context, but I think the best solution would be to fall back to a list of the current level of nesting, that should be reasonably sized.

**Comment by iamtakingiteasy** [comment]
By `<details>` I mean HTML element. It is supported by github flavor of markdown as well, you do
```
<details>
<summary>Some summary</summary>
and some content
</details>
```

<details>
<summary>Some summary</summary>
and some content
<details>
<summary>Some nested summary</summary>
and some nestedcontent
</details>
</details>

Almost exactly how current menu expanding works even without any styling, with no JS involved. With little CSS it can be turned in what you have now, but without jquery.

I still think some variant of "Everything in one page" at least for navigation, which would demand no dynamic loading, but allow to quickly overview everything documentation has to offer on one page searchable with standard browser functionality is required for basic convenience.

To avoid blowing up file sizes where such navigation is supposed to be included, you can have navigation in iframe, this way it can be included as separate file from any other and it can have just a bunch of nested expandable \<details\/\> tags.

**Comment by MathieuDuponchelle** [comment]
> To avoid blowing up file sizes where such navigation is supposed to be included, you can have navigation in iframe

Ah I see, can the iframe be made to integrate seamlessly into the page ooc?

**Comment by iamtakingiteasy** [comment]
Yes, simply styling away it's borders should make it seamless.

```css
iframe {
  background-color: transparent;
  border: 0px none transparent;
  padding: 0px;
}
```

https://jsfiddle.net/1qybjru7/

**Comment by MathieuDuponchelle** [comment]
I see, thanks :) Can you update this issue title to "move site navigation to an iframe" ? :)

**Comment by MathieuDuponchelle** [comment]
for now the result is only visible publicly at https://hotdoc.github.io/extensions.html , GStreamer will need an update of the lumen theme, @thiblahute do you care to release an updated version so I can test behavior locally first?
