### ISSUE TITLE
Make feedgen an optional runtime dependency

### ISSUE THREAD

**Issue by benjamb** [hotdoc/hotdoc#261]
We make use of hotdoc when building the Freedesktop-SDK runtime since gstreamer requires it to build its docs, it doesn't however require the use of the ATOM feed generation. Given that and the fact feedgen hasn't received any maintenance in over 3 years, it would be nice if feedgen were an optional dependency so that we cut out the dead weight.

**Comment by MathieuDuponchelle** [comment]
agreed, patch welcome :)
