### ISSUE TITLE
React Dev Tools break the left navigation panel

### ISSUE THREAD

**Issue by vitoyucepi** [hotdoc/hotdoc#271]
## Summary
I've found out that the React Developer Tools extension for Chrome/Firefox breaks the navigation panel on hotdoc websites.
One of them is https://gstreamer.freedesktop.org/documentation/gstreamer/gi-index.html.
I noticed that the same behavior can be seen on the official Hotdoc page at https://hotdoc.github.io.

## To reproduce

1. Enable React Dev Tools browser extension for Chrome/Firefox.
1. Visit https://hotdoc.github.io.
1. Try to scroll the left navigation panel.

https://github.com/hotdoc/hotdoc/assets/35035879/71897675-14e6-46cf-a5d6-8f95c3fb49de

## Expected behavior

The navigation panel can be scrolled without resetting to its original position.

## Additional
Bug report in the GStreamer bug tracker: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/3070.
Bug report in the React bug tracker: https://github.com/facebook/react/issues/27578.

**Comment by MathieuDuponchelle** [comment]
@vitoyucepi the navigation is an iframe and the main window communicates with it through a message to make it scroll to the current page. This is probably the listener the react person was talking about: https://github.com/hotdoc/hotdoc_bootstrap_theme/blob/master/src/js/navigation.js#L29 , it would seem like quite a coincidence that react also uses an `{action: "unfold"}` message, but perhaps using a `hotdoc-` prefix could make things safer?

**Comment by vitoyucepi** [comment]
Hi @MathieuDuponchelle,
Sorry, but I'm not very familiar with the hotdoc sources.
It would be great if you could test the `hotdoc-unfold`, or `hotdoc/unfold`.
Maybe assigning a namespace for all messages will be a great idea in case of integration with other libraries.

**Comment by MathieuDuponchelle** [comment]
OK, let me give it a try then

**Comment by MathieuDuponchelle** [comment]
@vitoyucepi that was indeed the problem. I have pushed an update and you should already be able to confirm the issue is fixed on <hotdoc.github.io>, the fix will then eventually trickle in to the gstreamer documentation.

Thanks again for reporting the issue :)
