### ISSUE TITLE
element-type can have two types in a GArray

### ISSUE THREAD

**Issue by dabrain34** [hotdoc/hotdoc#289]
In the case of Vulkan, see following [issue](https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/7880#note_2658309), the GArray can contain either VkImageMemoryBarrier or VkImageMemoryBarrier2KHR decided at compile time.

What would be the option to keep the documentation but dont tell the type of the element of the return value ?

**Comment by MathieuDuponchelle** [comment]
Commented there, not a hotdoc issue, closing :)
