### ISSUE TITLE
unable to uninstall hotdoc installed with setup.py

### ISSUE THREAD

**Issue by dabrain34** [hotdoc/hotdoc#291]
I installed hotdoc using the `setup.py` script but did not find anyway to uninstall it and backup to use the pip installed version for example.

**Comment by MathieuDuponchelle** [comment]
As mentioned in the installation doc, you should probably use pip to install instead, `setup.py` does not have an uninstall method. In any case, you should also use a virtual env to test changes, once you're done you can simply exit it :)

**Comment by dabrain34** [comment]
The idea would be to implement one. how complicated is that ?

**Comment by dabrain34** [comment]
it is now on my machine

**Comment by MathieuDuponchelle** [comment]
Just `rm -rf` whatever folder got created in your python's `site-packages`?
