### ISSUE TITLE
File inclusion: regex-based parsing can fail in some cases

### ISSUE THREAD

**Issue by MathieuDuponchelle** [hotdoc/hotdoc#48]
The simplest test case is to create a markdown index containing:

```
{{ Shouldn't try to include this }}
```

The includer should not try to include this ^^

**Comment by thiblahute** [comment]
I do not agree with that, it was a purpose to be able to have includes inside code blocks as we most probably include *code* in there.

**Comment by MathieuDuponchelle** [comment]
This is too much of a deviation from CommonMark IMHO, so-called "code blocks" are supposed to contain pre-formatted content, and I think it is fair to assume that this content will not be parsed and interpreted as markdown

**Comment by MathieuDuponchelle** [comment]
That is solved now
