### ISSUE TITLE
Add --version command line argument

### ISSUE THREAD

**Issue by pwithnall** [hotdoc/hotdoc#50]
It would be nice if `hotdoc` printed its version information when run as `hotdoc --version`, as is the convention.

**Comment by MathieuDuponchelle** [comment]
Will be the case in next released version.

**Comment by MathieuDuponchelle** [comment]
Done in https://github.com/hotdoc/hotdoc/commit/d27ad747a0affcafc30668069d00bebdfbf6be86 , incredible engineering achievement I know :P
