### ISSUE TITLE
Support anchors in headings

### ISSUE THREAD

**Issue by pwithnall** [hotdoc/hotdoc#51]
It’s very useful to be able to cross-reference different headings within the same page. gtk-doc supported `## My Heading {#my-heading-anchor}` syntax (which I think is used by a few other flavours of Markdown, but not CommonMark) for this.

grep for `heading-two` on https://developer.gnome.org/gtk-doc-manual/unstable/documenting_syntax.html.en#documenting_syntax for an example

Something equivalent would be very useful.

**Comment by MathieuDuponchelle** [comment]
Already implemented, see --html-add-anchors and https://people.collabora.com/~meh/hotdoc_hotdoc/html/syntax-extensions.html#referencing-another-page , this link uses that feature by the way ;)
