### ISSUE TITLE
Can't put html inside a piped table

### ISSUE THREAD

**Issue by ocrete** [hotdoc/hotdoc#54]
I expected something like this to work:

| < span style="color: red">red text </ span> | bb |
|-|-|
| cc  | dd

**Comment by MathieuDuponchelle** [comment]
It now works, though your example will not be accepted as valid html by cmark,
you need no space before tag names, like so:

```
< span>< /span> // won't work
<span></span> // will work
```

You can also now use headerless tables, iirc you asked for that at some point, just omit the header row:

```
| -- | -- |
| c1 | c2 |
```
