### ISSUE TITLE
Feature request: pandoc-style implicit link definition for headings

### ISSUE THREAD

**Issue by smcv** [hotdoc/hotdoc#55]
Hotdoc can currently do this:

```markdown
## Some heading
blah blah
## Some other heading
As I said in [](#some-heading), ...
```

and have it interpreted as "As I said in _Some other heading_, ..." with a hyperlink. This works because it automatically generates `<a id="some-heading">` from the text of the heading itself, and because as a (Hotdoc-specific?) shortcut, omitting the title of a hyperlink makes Hotdoc infer it from the destination.

This requires the author of the Markdown document to know how Hotdoc will mangle a heading title into a `string-suitable-for-anchors`, which is not necessarily trivial if it contains punctuation or even markup.

Pandoc's spelling for this (which seems to be a commonly available shortcut in other parsers) is:

```markdown
## Some heading
blah blah
## Some other heading
As I said in [Some heading], ...
```

(or equivalently the same thing with `[Some heading][]`). Effectively, it behaves as though the author had written the first section as:

```markdown
## <a id="some-heading">Some heading</a>
blah blah
[Some heading]: #some-heading
```

except that if the author writes an explicit link definition `[Some heading]: ...`, it takes precedence over the one generated by this shortcut.

This seems very much like the [Markdown philosophy](https://daringfireball.net/projects/markdown/syntax#philosophy): the writer writes nice human-readable text that matches the heading, and Pandoc transforms it into the machine-readable form (the anchor syntax).

**Comment by smcv** [comment]
This is not necessarily very useful in gtk-doc-style API references, but it's a useful trick in larger documents like tutorials or design documentation.

**Comment by smcv** [comment]
The other nice thing about the Pandoc style is that because Markdown link references are explicitly case-insensitive, you can refer to a heading using the case combination that is natural for the reference:

```
More information about [running Hotdoc] can be found later in this document.
…
## Running Hotdoc
…
```

would naturally render to

> … information about [running Hotdoc](#) can be …

whereas

```
More information about [](#running-hotdoc) can be found later in this document.
…
## Running Hotdoc
…
```

would render to

> … information about [Running Hotdoc](#) can be …

unless you repeat yourself.

**Comment by MathieuDuponchelle** [comment]
Implemented, thanks for the report!
