### ISSUE TITLE
invisible link if %FALSE %TRUE are not properly parsed

### ISSUE THREAD

**Issue by gdesmott** [hotdoc/hotdoc#58]
I uses 
`* Returns: %TRUE if the operation succeeded, %FALSE otherwise"` 
but TRUE and FALSE are not displayed in the generated html:
`<a href="TRUE"></a> if the operation succeeded, <a href="FALSE"></a> otherwise</p>`

That seems to be because I'm lacking /usr/share/gtk-doc/html/glib/index.sgml but in any case, a better fallback would be good.

**Comment by MathieuDuponchelle** [comment]
looking at this now, thanks !

**Comment by MathieuDuponchelle** [comment]
Fixed by https://github.com/hotdoc/hotdoc/commit/38bf305435044bca323e750b75e3498d3e35d6a7, tnx!
