### ISSUE TITLE
Running "hotdoc" does nothing

### ISSUE THREAD

**Issue by ocrete** [hotdoc/hotdoc#60]
If I just run "hotdoc" it does nothing, and prints nothing.. And I'm confused every time.

My preference would be to do "hotdoc run", as this is the most likely use.

But you could also print a short usage message.

I also can't find what the other possible options are, the "--help" says there is "conf" too, but that also seems to not nothing ?

**Comment by MathieuDuponchelle** [comment]
Fixed, thanks. Regarding conf, its sole purpose for now is to allow you to pass a command line and get a json file, it may be deprecated by the fact that anyway one is now always saved in $(output_dir)
