### ISSUE TITLE
Spell languages' and protocols' names correctly

### ISSUE THREAD

**Issue by smcv** [hotdoc/hotdoc#62]
**To reproduce:** generate documentation for e.g. https://git.apertis.org/cgit/canterbury.git/

**Expected result:** C, D-Bus, JavaScript and Python are consistently referred to as such in user-facing files (but not necessarily in filenames, etc.). In particular, JavaScript canonically has intercapitalization, and the protocol is called D-Bus; dbus is the reference implementation of D-Bus, and there is no DBus or Dbus.

**Actual result:** the Docbook "books" refer to "c", "javascript", "python", "dbus" and "Dbus" (which I assume is "dbus", title-cased); the standalone HTML refers to "Javascript" (which I assume is the result of applying title-case).

**Comment by MathieuDuponchelle** [comment]
Fixed, will now refer to D-Bus API Reference, GObject API Reference etc ..

As devhelp upstream is OK with enabling javascript, we'll only install one book now, which means we won't need to specify the language of each book that is output.
