### ISSUE TITLE
Should not display GObject _IS_ macros

### ISSUE THREAD

**Issue by gdesmott** [hotdoc/hotdoc#66]
See https://git.collabora.com/cgit/user/cassidy/apertis/traprain.git/log/?h=doc

The generated doc contains macros such as TRP_CLIENT_IS_MOCK which are generated using G_DECLARE_FINAL_TYPE().
They macros are generally not part of the API documentation so it would be good to have an easy way to get rid of them.

**Comment by MathieuDuponchelle** [comment]
Please note these are *not* macros, which is why you end up seeing them. I'll see what I can do to filter these out anyway.

**Comment by MathieuDuponchelle** [comment]
Fixed (though not very elegantly, but there's not much I can do here), will release later today., thanks!
