### ISSUE TITLE
Doc contains weird "Exported Variables"

### ISSUE THREAD

**Issue by gdesmott** [hotdoc/hotdoc#67]
See html/c/traprain-service-navigation.html generated from https://git.collabora.com/cgit/user/cassidy/apertis/traprain.git/log/?h=doc

The doc contains 3 "Exported Variables" :  __inst __t and __r which seems related to the magic from G_DECLARE_FINAL_TYPE()

**Comment by MathieuDuponchelle** [comment]
Very related to #66 , will see what I can do at the same time :)

**Comment by MathieuDuponchelle** [comment]
Fixed, will release later today, thanks!

**Comment by MathieuDuponchelle** [comment]
`pip install hotdoc_gi_extension --upgrade` :)
