### ISSUE TITLE
Directory hierarchy not maintained in html output tree

### ISSUE THREAD

**Issue by tp-m** [hotdoc/hotdoc#73]
If I use `foo/bar.md` in `sitemap.txt`, hotdoc will output `bar.html` at the top-level in the build directory. The subdirectory structure is not maintained. I would consider this a bug, or at least it should be an option IMHO, since if there's a `bar/bar.md` it would get clobbered in the single output dir.

**Comment by MathieuDuponchelle** [comment]
Thanks for the report :)
