### ISSUE TITLE
Feature request: Add a switch to generate the list of files output by hotdoc for a given project.

### ISSUE THREAD

**Issue by MathieuDuponchelle** [hotdoc/hotdoc#8]
This will allow avoiding the usage of a stamp file in build systems.

**Comment by pwithnall** [comment]
See `glib-compile-resources --generate-dependencies` for an example. Or the [GNU Make manual](https://www.gnu.org/software/make/manual/html_node/Automatic-Prerequisites.html).

**Comment by MathieuDuponchelle** [comment]
This is fixed in a way similar to gcc now, closing thanks.

**Comment by MathieuDuponchelle** [comment]
https://user-images.githubusercontent.com/1278273/103042142-ed074200-4578-11eb-8305-266b3e5dbc9f.mp4
