### ISSUE TITLE
Links to specific pages broken

### ISSUE THREAD

**Issue by gdesmott** [hotdoc/hotdoc#81]
Take `git+ssh://git.apertis.org/git/traprain.git` master (`afe13763af3f2d7378a24630a71cfee64dfa9146`) and build its doc.

I get those warnings
```
WARNING: [core]: (markdown-bad-link): /home/cassidy/dev/bosch/git/traprain/docs/reference/markdown_files/traprain-overview.markdown: Trying to link to non-existing identifier ‘traprain-service-navigation.html’
WARNING: [core]: (markdown-bad-link): /home/cassidy/dev/bosch/git/traprain/docs/reference/markdown_files/traprain-overview.markdown: Trying to link to non-existing identifier ‘traprain-common-route.html’
WARNING: [core]: (markdown-bad-link): /home/cassidy/dev/bosch/git/traprain/docs/reference/markdown_files/traprain-overview.markdown: Trying to link to non-existing identifier ‘traprain-client-navigation.html’
WARNING: [core]: (markdown-bad-link): /home/cassidy/dev/bosch/git/traprain/docs/reference/markdown_files/traprain-overview.markdown: Trying to link to non-existing identifier ‘traprain-client-mock.html’
```

I'm pretty sure those use to work at some point. But that's ok, I can easily fix the links by changing for example `[TrpServiceNavigation](traprain-service-navigation.html)` to `[TrpServiceNavigation](traprain-service/navigation.html)`.
Then the links in the generated page are working as expected, but Hotdoc still claims they are broken when building:

```
WARNING: [core]: (markdown-bad-link): /home/cassidy/dev/bosch/git/traprain/docs/reference/markdown_files/traprain-overview.markdown: Trying to link to non-existing identifier ‘traprain-service/navigation.html’
WARNING: [core]: (markdown-bad-link): /home/cassidy/dev/bosch/git/traprain/docs/reference/markdown_files/traprain-overview.markdown: Trying to link to non-existing identifier ‘traprain-common/route.html’
WARNING: [core]: (markdown-bad-link): /home/cassidy/dev/bosch/git/traprain/docs/reference/markdown_files/traprain-overview.markdown: Trying to link to non-existing identifier ‘traprain-client/navigation.html’
WARNING: [core]: (markdown-bad-link): /home/cassidy/dev/bosch/git/traprain/docs/reference/markdown_files/traprain-overview.markdown: Trying to link to non-existing identifier ‘traprain-client/mock.html’
```

I'm using
```
hotdoc==0.8.3
hotdoc-c-extension==0.8.2
hotdoc-dbus-extension==0.8
```

**Comment by gdesmott** [comment]
Yes, linking to the symbol directly does work. But I want the link to point to the "overview" section of the page, not the description of the opaque object structure.

**Comment by MathieuDuponchelle** [comment]
right, so TrpServiceNavigation::TrpServiceNavigation then ?

**Comment by MathieuDuponchelle** [comment]
iirc you might also be able to link to `[foo](traprain-service/navigation.h)` , needs to be tested though

**Comment by gdesmott** [comment]
`TrpServiceNavigation::TrpServiceNavigation` links to the top of the object hierarchy so just after the 'section' block, which is exactly what I want.

As said in the report, `[foo](traprain-service/navigation.h)` does work but hotdoc still complains about it.

**Comment by MathieuDuponchelle** [comment]
@gdesmott , the "works but complains" case you reported is for `[TrpServiceNavigation](traprain-service/navigation.html)` , what I'm suggesting here is `[foo](traprain-service/navigation.h)` :)

**Comment by gdesmott** [comment]
Oh sorry; indeed this one is working! Thanks :+1: 

Should we let the bug opened for the "work but complain" case?

**Comment by MathieuDuponchelle** [comment]
Hm I think that's something fixed here, let's just close this one :)
