### ISSUE TITLE
Generated HTML pages not updated when sitemap.txt is updated

### ISSUE THREAD

**Issue by gdesmott** [hotdoc/hotdoc#83]
- Take git+ssh://git.apertis.org/git/traprain.git master (afe13763af3f2d7378a24630a71cfee64dfa9146) and build its doc.
- Then edit `sitemap.txt` and remove those lines:
```
	gi-index
	dbus-index
```
- Rebuild the doc then open `built_doc/html/index.html`
- The generated page still list the 2 subpages. Cleaning the build tree and rebuilding the whole thing make it disappear as expected.

I'm using
```
hotdoc==0.8.3
hotdoc-c-extension==0.8.2
hotdoc-dbus-extension==0.8
```

**Comment by MathieuDuponchelle** [comment]
Fixed :)
