### ISSUE TITLE
devhelp doc isn't very usable

### ISSUE THREAD

**Issue by gdesmott** [hotdoc/hotdoc#84]
The Traprain generated devhelp doc isn't great:

- No convenient header as with gtk-doc containing links to navigate inside the page (_Top_, _Description_, _Properties) and the rest of the doc (_Home_, _Up_, _Previous_, _Next).
- Style isn't great: no blue box around API declarations, etc
- There is a _Toggle navigation_ button at the top which doesn't do anything
- Just next to it there is a "missing icon" image
- There is a unsensitive _Fetching Index_ entry doing nothing

```
ii  hotdoc                                 0.8.3-0co1bs1                                amd64        tastiest documentation tool
ii  hotdoc-c-extension                     0.8-0co2bs1                                  amd64        c extension for hotdoc
ii  hotdoc-dbus-extension                  0.8-0co1bs1                                  all          DBus extension for hotdoc
ii  devhelp                                3.18.1-1ubuntu5br2                           amd64        GNOME developers help program
ii  devhelp-common                         3.18.1-1ubuntu5br2                           all          Common files for devhelp and its library
ii  libdevhelp-3-2                         3.18.1-1ubuntu5br2                           amd64        Library providing documentation browser functionality
```

Here is a screenshot with Apertis 16.12:

![dev](https://cloud.githubusercontent.com/assets/1379524/21541596/f53ce57a-cdb7-11e6-97b5-68db9d647385.png)

**Comment by MathieuDuponchelle** [comment]
It seems the assets (css / js) are somehow not installed correctly, fwiw here's a screenshot of hotdoc's documentation in devhelp on my end so you at least know what things should look like:

![screenshot from 2017-04-04 02-30-25](https://cloud.githubusercontent.com/assets/1278273/24637123/f7309210-18de-11e7-9a4e-d3a840362156.png)

Can you check whether the documentation renders correctly if you try to open it in a web browser ? If not, then you should be able to easily tell what's going on.

**Comment by thiblahute** [comment]
Working here, no info provided so I am closing. Reopen if you think it is necessary.
