### ISSUE TITLE
Unclear what of https://github.com/hotdoc is actually useful

### ISSUE THREAD

**Issue by gdesmott** [hotdoc/hotdoc#85]
https://github.com/hotdoc contains a lot of repositories and it's unclear which ones are still useful and which are deprecated (some have been merged to the main repo, right ?)

The description of the obsolete ones should be updated with a big **DEPRECATED** note, or may they should just be removed.

**Comment by MathieuDuponchelle** [comment]
Yep, just did some cleanup, transferred ownership of the extensions that have been merged in hotdoc back to me, things should be clearer now hopefully, thanks for the report!
