### ISSUE TITLE
`--output` directory should not be unconditionally wiped

### ISSUE THREAD

**Issue by ptomato** [hotdoc/hotdoc#86]
I've managed to shoot myself twice with this footgun when setting up a Hotdoc project: if you specify an already existing directory to `--output`, it is wiped without warning.

Ideally there would be a warning in the `--help` and the documentation that would tell you that the directory is wiped. Even more ideally, Hotdoc should just not erase files that it didn't create.

**Comment by MathieuDuponchelle** [comment]
That's right, sorry about that, hope it did not wipe any unsaved work ! The ideal case should not be too hard to implement, but I would anyway recommend setting `output` to a dedicated, non-existing folder.

**Comment by thiblahute** [comment]
Isnt it fixed now?

**Comment by ptomato** [comment]
Indeed, I tested with a build dir with a single file `foo.txt`, then `hotdoc run`; the `foo.txt` file was preserved.
