### ISSUE TITLE
Formatter needs more public API

### ISSUE THREAD

**Issue by ptomato** [hotdoc/hotdoc#96]
I've found it's difficult to write a simple formatter that builds on the default formatter, without dipping into private API. As a start, I think `Formatter._symbol_formatters`, `Formatter._ordering`, and `Formatter._format_linked_symbol()` would be good candidates for making public.

**Comment by MathieuDuponchelle** [comment]
All the methods and attributes prefixed by '_' are meant to be "protected", and overridable by subclasses. These methods are not meant to be *public* API, but I don't think that's what you actually want ?

**Comment by ptomato** [comment]
OK. Usually I would interpret the underscore as private API. In that case, never mind.

**Comment by thiblahute** [comment]
In hotdoc `__` means *private* - in that case the symbol name is even
mangled so it is really not usable from outside.
